### ISSUE TITLE
Прикрутить генетратор аналогично Yeoman

### ISSUE THREAD

**Issue by alexHlebnikov** [2gis/tars#34]
Идея: конфижить tars-config.js не после развертывания tars и ручками, а следующим шагом в консоли. Как, например, происходит при развертывании Yeoman.
Пример: выбор препроцессора.
![Выбор препроцессора в Yeoman.](http://yeoman.io/assets/img/codelab/image_8.5a17.png)

**Comment by artem-malko** [comment]
А какие опции пропускать через этот генератор?
Если все, то кажется, что это будет несколько утомительно. Что вытащить стоит?

**Comment by alexHlebnikov** [comment]
Можно самые важные выбрать, например: autoprefixerConfig, useSVG, browser, startUrl, templater, cssPreprocessor, useImagesForDisplayWithDpi

**Comment by artem-malko** [comment]
То есть в итоге ты все равно полезешь в конфиг?

**Comment by alexHlebnikov** [comment]
Ок. Вариант: на выбор пользователю генератор полного конфига или же экспрессс-генератор только самых важных моментов.

**Comment by artem-malko** [comment]
Можем запустить инит с ключом каким-нить? Если ключ передан, то основные настройки в консоли указываем, если нет — то говорим, что нужно лезть в файл конфигов. Как-то так.
Неизменяемые опции точно можно будет передать в этот генератор.

**Comment by alexHlebnikov** [comment]
Да, как-то так.

**Comment by artem-malko** [comment]
Поставлю в версию 1.3.0, а там посмотрим.

**Comment by TrySound** [comment]
В случае с препроцессорами хочется, чтобы и package.json менялся. А то тот же sass модуль 30 мб весит. И на медленном соединении надо жуть сколько ждать, пока npm отработает. Хотя больше смущает imagemin.

**Comment by artem-malko** [comment]
Тоже были такие мысли. Пока не в приоритете, но сделать это точно стоит.

**Comment by Grawl** [comment]
Я раньше пользовался [generator-yeogurt](https://github.com/larsonjj/generator-yeogurt), там весьма хорошо этот вопрос решён.

В общем, по-моему, было бы хорошо, чтобы вышло как-то так:

---

Hi, I'm TARS. I will help you to make awesome markup!

Let's choose some options:

**CSS tool**

- Sass
- SCSS
- Less
- Stylus
- Plain CSS with PostCSS

**HTML Templater**

- Handlebars
- Jade

**JS tool**

- Coffee
- TypeScript
- …
- Plain JS with ES'15 support

**Do you like to choose some *advanced* options?** (9 more)

- autoprefixerConfig
- useImagesForDisplayWithDpi
- browser
- …

---

Кстати, по-умолчанию можно для BrowserSync [указать браузер по-умолчанию](http://www.browsersync.io/docs/options/#option-browser), и я думаю, что это было бы лучше, чем навязывать всем Chrome :wink:

**Comment by TrySound** [comment]
А можно выбирать браузер, который в системе по умолчанию?

**Comment by Grawl** [comment]
Ну да. Я ж ссылку дал выше. `browser: 'default'`.

**Comment by artem-malko** [comment]
@Grawl насчет browser default – согласен.
Насчет генератора, тут пока не ясно. Я планировал туда передать только выбор препроцессора, шаблонизатора, имен для папок. Остальное человек настроит сам через конфиг.

**Comment by Grawl** [comment]
Я предложил самый удобный для пользователя вариант.

**Comment by artem-malko** [comment]
Будет свой CLI #48
