### ISSUE TITLE
Research about broccoli

### ISSUE THREAD

**Issue by alexHlebnikov** [2gis/tars#45]
Говорят, broccoli быстрее gulp. Надо бы исследовать эту тему.
https://github.com/broccolijs/broccoli

**Comment by artem-malko** [comment]
Пока стоит подождать, так как, насколько я понял из документации, проект еще в бета-версии находится.

**Comment by artem-malko** [comment]
* Not many plugins
* Quite small community

Will return to research about broccoli in the of 2015
