### ISSUE TITLE
More simple task defining

### ISSUE THREAD

**Issue by TrySound** [2gis/tars#55]
gulp.task must be defined outside of module.exports and executed once in one place.

**Comment by artem-malko** [comment]
I can't understand a problem. Every task have to be included into gulpfile. So function in exports will be executed only one time, while including into gulpfile. So there are no any extra function calls.

**Comment by TrySound** [comment]
It calls in old init.js for example

**Comment by artem-malko** [comment]
@TrySound do you mean requiring task in another task?

**Comment by TrySound** [comment]
Yes. Task defines twice

**Comment by artem-malko** [comment]
Will check it. I'll remove all extra requires if it's possible.

**Comment by TrySound** [comment]
All task dependencies must be defined by runSequence in gulpfile.js (it's like router)

**Comment by artem-malko** [comment]
Do you mean something like that:

```javascript
runSequence(
    require(taskName),
    cb
)
```

**Comment by TrySound** [comment]
No, sure. Everything like now, but not like this gulp.task('task', ['dep1'], function () {})
All tasks dependencies in gulpfile.js
