### ISSUE TITLE
Data defining

### ISSUE THREAD

**Issue by TrySound** [2gis/tars#56]
For data better use module.exports = {}; or at least {name: data} notation for clearer building code

**Comment by artem-malko** [comment]
@TrySound need more info. You want to replace eval, by exports?

**Comment by artem-malko** [comment]
@TrySound ip!

**Comment by TrySound** [comment]
Wrap by `module.exports = {}` when all data concatenates to prevent using `eval`

**Comment by artem-malko** [comment]
Not important. Will be implemented in patch version.

**Comment by TrySound** [comment]
Everything with eval very important. Don't let the evil be!-)

**Comment by artem-malko** [comment]
@TrySound yeah, but it's not important at this place)

**Comment by artem-malko** [comment]
@TrySound we can't use exports, cause Node has it's own cache for exports. And we need to reexport data on changing. Of course, we could use some hacks to clear Node cache, but it's not good idea.
