### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by TrySound** [2gis/tars#57]
Предлагаю в версии 2.0 отказаться от растеризации svg. Ветку 1.* можно попрежнему развивать как jQuery, но 2.0 писать на мастере.

**Comment by TrySound** [comment]
user-package.json - не лучшая идея. Все равно все пользуются npm i -D для установки, а не в ручную таски добавляет.

**Comment by artem-malko** [comment]
Не все используют npm i -D. Например, я никогда не использую эту команду. Поверь, я не один такой.
Не понял, как это связано с ручным добавлением тасков?

**Comment by artem-malko** [comment]
Обсуждение переместить в #59
