### ISSUE TITLE
browserSync.reload

### ISSUE THREAD

**Issue by TrySound** [2gis/tars#58]
Лучше его класть не в поток, а в стек runSequence в вотчере. Так логичнее и экономнее.

**Comment by artem-malko** [comment]
Почему экономнее?
Не на все места есть вотчер, после которых нужно перезагрузить браузер. Вотчеров может быть меньше, чем тасков.

**Comment by TrySound** [comment]
Everywhere in runSequence could be reload. But it will be called once after all tasks in stack.

**Comment by artem-malko** [comment]
Reload is executed after file changing. For example, you've changed *.html file, browser has been reloaded only one time. There are no any extra calling. So, i don't understand advantages of your idea.
I'll be agree to remove reload to watcher, but i think, that there are could be task without watchers.

**Comment by artem-malko** [comment]
@TrySound up!
