### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by pytkin** [2gis/tars#67]

**Comment by artem-malko** [comment]
Could you give some examples for .editorconfig? What kind of editors we can support by .editorconfig?

**Comment by pytkin** [comment]
Here [list of supported editors](http://editorconfig.org/#download).
Examples:  
- [Basic example on editorconfig.org](http://editorconfig.org/#example-file);
- [Bootstrap's editorconfig](https://github.com/twbs/bootstrap/blob/master/.editorconfig);
- [Foundation's editorconfig](https://github.com/zurb/foundation/blob/master/.editorconfig);
- [atom-editorconfig's editorconfig](https://github.com/sindresorhus/atom-editorconfig/blob/master/.editorconfig);
- (babel's editorconfig)[https://github.com/babel/babel/blob/master/.editorconfig].

**Comment by artem-malko** [comment]
We need to disscus all options. What is the most important thing? What should we add to editor. Let's start from one example and will edit it then.

**Comment by pytkin** [comment]
I'm using bootstrap config in my projects:
```
root = true

[*]
charset = utf-8 // set default charset for new documents.
end_of_line = lf // unix style line ending
indent_size = 2 // a whole number defining the number of columns used for each indentation level and the width of soft tabs (when supported).
indent_style = space // use tab or space for indents, this is important
insert_final_newline = true  // ensure file ends with a newline when saving, needed for unix
trim_trailing_whitespace = true // remove any whitespace characters preceding newline characters

[*.py] // for backend developers, sometimes I'm using [*.php] mask
indent_size = 4
```

I'm thinking that this is ideally config for tars:
```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 4
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

**Comment by artem-malko** [comment]
```
insert_final_newline = true
```
What is the main idea of this string?

**Comment by TrySound** [comment]
@artem-malko 
http://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file
http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline
http://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

**Comment by artem-malko** [comment]
@TrySound @pytkin I've just realised, that .editorconfig – it's not about TARS. TARS shouldn't take effect on environment. I think, what it would be not comfortable for that people, who do not use editorconfig. Other developers could add it by themself.
Is it possibly, to make this optional?

**Comment by artem-malko** [comment]
It's not necessary option.
