### ISSUE TITLE
Generate 2 js-files in build

### ISSUE THREAD

**Issue by senja006** [2gis/tars#76]
Хотелось бы иметь возможность при собирании проекта иметь 2 файла скриптов: в одном все вендорные скрипты, в другом собственные. Это необходимо для удобной правки скриптов на продакшене.

It'd be nice, if modules' js-files have been concatinated into 1 js-file in build, and static's js-files have been concatinated into another.

**Comment by artem-malko** [comment]
@senja006 как предлагаешь решить проблему?

How can we fix it?

**Comment by d6233** [comment]
Наверно, как и я предлагал, файлы из модулей собираются отдельно, называются main.js, а другие, те которые в static/js в файл vendor.js или assets.js...как то так

**Comment by senja006** [comment]
ага

**Comment by artem-malko** [comment]
@senja006 @d6233 Sourcemaps как-то могут помочь здесь? Без разделения js-а на два бандла?

Can sourcemaps be helpfull, without js dividing.

**Comment by senja006** [comment]
мне помогут. уже нет необходимости создавать 2 файла

**Comment by artem-malko** [comment]
@senja006 задачу закрываем?

**Comment by senja006** [comment]
да
