### ISSUE TITLE
SVG sprite problem? 

### ISSUE THREAD

**Issue by dumperize** [2gis/tars#82]
I did follow a manual: 
1. i am create svg file in markup\static\img\svg and named it people.svg
2. in markup\static\scss\GUI.scss i writed 
- - - 
.icon {
    &-people {
        @include bg-svg("people"); // Подключение svg-изображения
    }
}
- - - 
3. ... and had erorr in console 

- - -
"[16:22:33] index out of bounds for `nth($list, $n)` on line 2254 in C:/Users/Thi
nkPad/tars/markup/static/scss/main.css"
- - - 

i think i do something wrong. 
Please help me.

**Comment by artem-malko** [comment]
You have to use variable inside mixin.

```sass
@include bg-svg(@people);
```
