### ISSUE TITLE
Ошибки при сборке проекта

### ISSUE THREAD

**Issue by thisavoropaev** [2gis/tars#84]
При сборке проекта (gulp dev) на этих тасках возникают ошибки:

![2015-06-02 14 46 24](https://cloud.githubusercontent.com/assets/9802205/7935096/9eb02c22-0936-11e5-8a9f-aecfb671de56.png)

![2015-06-02 14 46 37](https://cloud.githubusercontent.com/assets/9802205/7935094/9e96d6d2-0936-11e5-96bf-b3cc4197ae40.png)

При этом создается исключительно директория dev (стандартный tars-config.js) с данной структурой:
![2015-06-02 14 52 30](https://cloud.githubusercontent.com/assets/9802205/7935146/30fde646-0937-11e5-8fcf-c1b1dd8f5ade.png)

Так же до этого почему-то не установился npm модуль digits и пришлось доустанавливать его руками.

Node и Gulp обновлены до последней версии, правда перед сборкой предупреждаем о том, что локальная версия gulp немного младше.

**Comment by Evrei** [comment]
Проверьте наличие .jscs файла в корне tars

**Comment by artem-malko** [comment]
@Evrei прав)

**Comment by thisavoropaev** [comment]
Скачал архив и прошел процедуру установки заново - его нет.

Проблема с тем, что не устанавливался модуль digits решилась добавлением флага --unsafe-perm к npm install.

**Comment by thisavoropaev** [comment]
Проблема была в том, что читая описание был скачан zip архив и распакован во временную папку, а после было скопировано все видимое содержимое. А файлы начинающиеся с . скопированы не были (у меня недавно был сброс настроек параметров системы и скрытые файлы не отображались, о чем я даже сам не знал).

Так что лучше напишите, что вместо скачивания архива делать git clone в нужную директорию, тогда бы такой проблемы не возникло.

P.S. Проблема с тем, что модуль digits не устанавливался со всеми остальными модулями через npm install решилась добавлением флага --unsafe-perm к npm install.

**Comment by artem-malko** [comment]
@thisavoropaev спасибо, учтем)
