### ISSUE TITLE
init throws exception

### ISSUE THREAD

**Issue by eddyLazar** [2gis/tars#85]
gulp init выбрасывает exception 
.../tars-master/node_modules/download/node_modules/each-async/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');

раньше не было такого 

платформа - Mac OS

**Comment by artem-malko** [comment]
@eddyLazar с какими настройками инититесь? Какая версия TARS используется?

**Comment by eddyLazar** [comment]
Думал что связанно с какими то моими скриптами, а потом установил голый тарс, ничего не менял сразу запустил инит и все равно выкинуло этот эксепшн. Может быть связанно с обновлениями в каких-то зависимостях?

**Comment by artem-malko** [comment]
@eddyLazar да вот не было обновлений зависимостей. Все же какая версия TARS и какая конфигурация?

**Comment by artem-malko** [comment]
@eddyLazar проблема еще повторяется?

**Comment by artem-malko** [comment]
Закрываю, так как не повторяется.
